name: "typescript action"
author: "Rodrigo"
description: "leer parametros del action.yaml"

inputs:
  method: 
  applicationName: 
  applicationVersion: 
  currentBranch: 
  appCommitId:
  
runs:
  using: node16
  main: 'dist/index.js'
