...
name: approver-pro
on:
  push:
    branches: [ "workflows" ]
  workflow_dispatch:
    inputs:
      deploy:
        default: ""
        description: test
        required: true
jobs:

  approve-workflow:
    if: github.actor == 'rodrigociro' || github.actor == 'rodrigociro'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_RODRIGO }}
    - name: Get environment id
      uses: actions/github-script@v6
      id: environment-id
      with:
        script: |
          const environmentResponse = await github.rest.repos.getEnvironment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            environment_name: 'pro'
          });
          const environmentId = environmentResponse.data.id;
          console.log("Env:", environmentId);
          return environmentId;

    - name: Approve workflow
      uses: actions/github-script@v6
      env:
        GH_TOKEN: ${{ secrets.PAT_RODRIGO }}
      with:
        github-token: ${{ secrets.PAT_RODRIGO }}
        script: |
          await github.rest.actions.reviewPendingDeploymentsForRun({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.runId,
            environment_ids: [${{ steps.environment-id.outputs.result }}],
            state: 'approved',
            comment: 'approve by dmp-bot!',
          });