name: Control-M Master
on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
jobs:
  Deployment-PRE:
    runs-on: ${{ inputs.runner }}
    environment: pre
    steps:
    - uses: actions/checkout@v3
    - name: codigo de ControlM
      run: |
        echo "Here we execute the CURLs command to login,patch the JSON and create JACD to Control-M PRE"
