name: Control-M Integration Branch
on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      isRelease:
        required: true
        type: string
jobs:
  Deployment-DEV:
    runs-on: ${{ inputs.runner }}
    environment: dev
    steps:
    - uses: actions/checkout@v3
    - name: codigo de ControlM
      run: |
        echo "código de control M en DEV"
        
  isRelease:
    runs-on: ${{ inputs.runner }}      
    if: "${{ github.event.inputs.level == 'true' }}"
    run: |
      echo "mi input vale ${{ inputs.isRelease }}"