name: Control-M Master
on:
  workflow_call:
    inputs:
      runner:
        required: true
jobs:
  Deployment-PRE:
    runs-on: ${{ inputs.runner }}
    environment: pre
    steps:
    - uses: actions/checkout@v3
    - name: codigo de ControlM
      run: |
        echo "código de control M"
