name: Control-M Integration Branch
on:
  workflow_call:
    inputs:
      runner:
        required: true
      isRelease:
        required: true  
jobs:
  Deployment-DEV:
    runs-on: ${{ inputs.runner }}
    environment: dev
    steps:
    - uses: actions/checkout@v3
    - name: codigo de ControlM
      run: |
        echo "código de control M en DEV"