name: dmp-azure-registry-promoter
on:
  push:
    branches: [ "dmp-azure" ]
  pull_request:
    branches: [ "dmp-azure" ]
  
  workflow_dispatch:
    inputs:
      deploy:
        description: "Azure Target Registry"
        required: true
        default: 'false'
      azure_source_registry:
        description: "Azure Source Image"
        required: true
      azure_source_image:
        description: "Azure Target Registry"
        required: true
      azure_target_registry:
        description: "para desplegar"
        required: true
      azure_subscription:
        description: "Azure Subscription"
        required: true
      azure_credentials:
        description: "Azure Credentials"
        required: true

jobs:
  docker_image_promotion:
    runs-on: ubuntu-latest
    steps:
    - name: Execute Azure Promoter
      if: ${{ github.event.inputs.deploy == 'True' }}
      env:
        AZURE_SECRET: ${{ secrets.MI_SECRET_AZURE }}
      run: |
        echo "Azure Source Registry: ${{ github.event.inputs.azure_source_registry }}"
        echo "Azure Source Image: ${{ github.event.inputs.azure_source_image }}"
        echo "Azure Target Registry: ${{ github.event.inputs.azure_target_registry }}"
        echo "Azure Subscription: ${{ github.event.inputs.azure_subscription }}"
        echo "Azure Credentials: ${{ github.event.inputs.azure_credentials }} y mi secreto es ${AZURE_SECRET}"

