name: dmp-azure-registry-promoter
on:
  on:
  push:
    branches: [ "dmp-azure" ]
  pull_request:
    branches: [ "dmp-azure" ]
  workflow_dispatch:
    inputs:
      deploy:
        description: 
        required: true
        default: 'false'
      azure_source_registry:
        description: 
        required: true
      azure_source_image:
        description: 
        required: true
      azure_target_registry:
        description: 
        required: true
      azure_suscription:
        description: 
        required: true
      azure_credentials:
        description: 
        required: true

jobs:
  docker_image_promotion:
    runs-on: DEV
    steps:
    - uses: name: Paso 2
        if: ${{ github.event.inputs.deploy == 'true' }} 
        run: |
          echo ${github.event.inputs.azure_source_registry}
          echo ${github.event.inputs.azure_source_image}
          echo ${github.event.inputs.azure_target_registry}
          echo ${github.event.inputs.azure_suscription}
          echo ${github.event.inputs.azure_credentials}

