name: dmp-azure-registry-promoter
on:
  push:
    branches: [ "dmp-azure" ]
  pull_request:
    branches: [ "dmp-azure" ]
  
  workflow_dispatch:
    inputs:
      deploy:
        description: "para desplegar"
        required: true
        default: 'false'
      azure_source_registry:
        description: "para desplegar"
        required: true
      azure_source_image:
        description: "para desplegar"
        required: true
      azure_target_registry:
        description: "para desplegar"
        required: true
      azure_suscription:
        description: "para desplegar"
        required: true
      azure_credentials:
        description: "para desplegar"
        required: true

jobs:
  docker_image_promotion:
    runs-on: ubuntu-latest
    steps:
    - name: Paso 2
      if: ${{ github.event.inputs.deploy == 'True' }} 
      run: |
        echo "Azure Source Registry: ${{ github.event.inputs.azure_source_registry }}"
        echo "Azure Source Image: ${{ github.event.inputs.azure_source_image }}"
        echo "Azure Target Registry: ${{ github.event.inputs.azure_target_registry }}"
        echo "Azure Subscription: ${{ github.event.inputs.azure_subscription }}"
        echo "Azure Credentials: ${{ github.event.inputs.azure_credentials }}"

