on: push
name: Jira Example
jobs:
  prueba:
    runs-on: ubuntu-latest
    name: Jira Example
    steps:
    - uses: actions/checkout@v3
    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - uses: atlassian/gajira-create@v3
      with:
        project: PRJ
        issuetype: Task
        summary: Build completed for ${{ github.repository }}
        description: Compare branch
        fields: '{"customfield_10171": "test"}'

    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"