name: typescript action
on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      repo: 
        required: true
        type: string
    outputs:
      jira:
        description: id jira ticket
        value: ${{ jobs.register_app_dmp.jira_id }}

jobs:
  register_app_dmp:
    runs-on: ${{ inputs.runner }}
    outputs:
      jira_id: ${{ steps.dmp.outputs.jira_id }}
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      id: dmp
      with:
        method: 'POST'
        applicationName: ${{ inputs.repo }}
        applicationVersion: '1.00.00'
        dmpAppIp: ''
        currentBranch: 'master'
        appCommitId: ''