name: typescript action
on:
  push:
    branches: [ "dmp-api" ]
  pull_request:
    branches: [ "dmp-api" ]
  workflow_dispatch:

jobs:
  register_app_dmp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      id: dmp
      env:
        dmpAppId: ${{ secrets.DMP_ID }}
      with:
        method: 'GET'
        applicationName: 'tsc-init'
        applicationVersion: '1.00.00'
        currentBranch: 'master'
        appCommitId: 'a'