on: push
name: Jira Example
jobs:
  prueba:
    runs-on: ubuntu-latest
    name: Jira Example
    steps:
    - uses: actions/checkout@v3
    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_BASE_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_BASE_TOKEN }}

    - name: Jira TODO
      uses: atlassian/gajira-todo@v3
      with:
        project: PRJ
        issuetype: Task
        description: Created automatically via GitHub Actions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}