name: read files
on:
  push:
    branches: [ "read-files" ]
  pull_request:
    branches: [ "read-files" ]
  workflow_dispatch:
jobs:
  trabajo1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
       parameter: "file.json"
       other_name: "file.yaml"