name: typescript action
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  trabajo1:
    runs-on: ubuntu-latest
    steps:
    - uses: ./
      with:
       entrada1: "rodrigo"
       entrada2: "espinoza"
