name: typescript action
on:
  push:
    inputs:
      runner: ubuntu-latest
        required: true
        type: string
      repo: tsc-init
        required: true
        type: string

jobs:
  register_app_dmp:
    runs-on: ${{ inputs.runner }}
    outputs:
      jira_id: ${{ steps.dmp.outputs.jira_id }}
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      id: dmp
      env:
        dmpAppId: ${{ secrets.dmp_id }}
      with:
        method: 'POST'
        applicationName: ${{ inputs.repo }}
        applicationVersion: '1.00.00'
        currentBranch: 'master'
        appCommitId: 'a'