name: read files
on:
  push:
    branches: [ "read-files" ]
  pull_request:
    branches: [ "read-files" ]
  workflow_dispatch:
jobs:
  trabajo1:
    runs-on: ubuntu-latest
    outputs:
      prueba: ${{ steps.testeando.outputs.prueba }}
    steps:
    - uses: actions/checkout@v3
    - name: testeando
      uses: ./
        with:
         parameter: "file.json"
         other_name: "file.yml"
  trabajo2:
    needs: ['trabajo1']
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.job1.outputs.prueba }}